/** All public routes, used by the sitemap and for reference. Slugs match the live site. */
export const pageRoutes = [
  "/",
  "/about-us/",
  "/who-we-serve/",
  "/sustainable-practices/",
  "/careers/",
  "/faqs/",
  "/contact-us/",
  "/referral/",
  "/manufacturer-certification/",
  "/privacy-policy/",
  // shelters & products
  "/shelters/",
  "/telecom-shelters/",
  "/datacomm-pro-series/",
  "/shelter-showcase/",
  "/shelter-transformation/",
  "/shelters-for-sale/",
  "/hvac-units/",
  "/cabinets/",
  "/generators/",
  "/generator-install/",
  "/cell-on-wheels/",
  // civil & services
  "/civil-construction/",
  "/civil-services-showcase/",
  "/installation-integration/",
  "/installation-commissioning/",
  "/general-site-maintenance/",
  "/site-decommissioning/",
  "/guy-tower-rod-inspections/",
  "/disaster-recovery/",
  "/engineering-drawings/",
  "/craning-logistics/",
  "/data-center-mec/",
  "/site-survey/",
  "/site-build-prep-development/",
  "/staging-services/",
  "/recycle-upgrade/",
  "/other-isp-services/",
  // ebooks
  "/ebook-telecom-construction/",
  "/ebook-energy-efficiency/",
  "/ebook-datacomm-pro-series/",
];

export const blogRoutes = [
  "/blog/",
  "/keeping-infrastructure-cool/",
  "/elevating-telecom/",
  "/roof-sealant-shelters/",
  "/site-analysis-permitting/",
  "/enhancing-isp/",
  "/wheres-the-money/",
  "/sites-done-right/",
  "/shutting-down-sites/",
];
