import { chromium } from 'playwright-core';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox','--disable-gpu'] });
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } });
await ctx.route('**/*', r => (r.request().url().includes('localhost')) ? r.continue() : r.abort());
const page = await ctx.newPage();
await page.goto(process.argv[2], { waitUntil: 'networkidle', timeout: 30000 }).catch(()=>{});
await page.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=700){window.scrollTo(0,y);await new Promise(r=>setTimeout(r,40));}window.scrollTo(0,0);});
await page.waitForTimeout(800);
await page.screenshot({ path: process.argv[3], fullPage: true });
await b.close(); console.log('ok');
